- name: Install npm and Docker on EC2 instance (Ubuntu)
  hosts: ec2_instances
  become: yes
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Node.js and npm
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Install Docker 
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Add ubuntu user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Check npm version
      ansible.builtin.command: npm --version
      register: npm_version
      changed_when: false

    - name: Check Docker version
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false

    - name: Display versions
      ansible.builtin.debug:
        msg:
          - "npm version: {{ npm_version.stdout }}"
          - "Docker version: {{ docker_version.stdout }}"